// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by BiglandsEngine Shader Mixin Code Generator.
// To generate it yourself, please install BiglandsEngine.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

// Nothing to generate
