blank_issues_enabled: false

contact_links:
  - name: BiglandsEngine Docs
    url: https://github.com/BiglandsEngine3d/BiglandsEngine-docs/issues
    about: Please report documentation issues in the BiglandsEngine Docs repository.

  - name: BiglandsEngine Website
    url: https://github.com/BiglandsEngine3d/BiglandsEngine-website/issues
    about: Please report website issues in the BiglandsEngine Website repository.

  - name: BiglandsEngine Community Toolkit
    url: https://github.com/BiglandsEngine3d/BiglandsEngine-community-toolkit/issues
    about: Please report community toolkit issues in the BiglandsEngine Community Toolkit repository.
