// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by BiglandsEngine Shader Mixin Code Generator.
// To generate it yourself, please install BiglandsEngine.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using BiglandsEngine.Core;
using BiglandsEngine.Rendering;
using BiglandsEngine.Graphics;
using BiglandsEngine.Shaders;
using BiglandsEngine.Core.Mathematics;
using Buffer = BiglandsEngine.Graphics.Buffer;

namespace BiglandsEngine.Rendering.Voxels
{
    public static partial class VoxelIsotropicSamplerKeys
    {
        public static readonly ValueParameterKey<float> maxBrightness = ParameterKeys.NewValue<float>();
    }
}
