// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by BiglandsEngine Shader Mixin Code Generator.
// To generate it yourself, please install BiglandsEngine.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using BiglandsEngine.Core;
using BiglandsEngine.Rendering;
using BiglandsEngine.Graphics;
using BiglandsEngine.Shaders;
using BiglandsEngine.Core.Mathematics;
using Buffer = BiglandsEngine.Graphics.Buffer;

using BiglandsEngine.Rendering.Materials;
using BiglandsEngine.Rendering.Voxels;
namespace BiglandsEngine.Rendering.Voxels
{
    internal static partial class ShaderMixins
    {
        internal partial class VoxelizeToFragmentsEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "VoxelizeToFragments");
                if (context.GetParam(VoxelizeToFragmentsKeys.Storage) != null)
                {

                    {
                        var __mixinToCompose__ = (context.GetParam(VoxelizeToFragmentsKeys.Storage));
                        var __subMixin = new ShaderMixinSource();
                        context.PushComposition(mixin, "Storage", __subMixin);
                        context.Mixin(__subMixin, __mixinToCompose__);
                        context.PopComposition();
                    }
                }
                if (context.GetParam(VoxelizeToFragmentsKeys.RequireGeometryShader) == true)
                {
                    mixin.AddMacro("RequireGeometryShader", true);
                    mixin.AddMacro("GeometryShaderMaxVertexCount", context.GetParam(VoxelizeToFragmentsKeys.GeometryShaderMaxVertexCount));
                }
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("VoxelizeToFragmentsEffect", new VoxelizeToFragmentsEffect());
            }
        }
    }
}
